name: Release Current Repo

on:
  workflow_dispatch: # 手动触发支持
  push:
    tags:
      - 'v*' # 监听以 'v' 开头的 tag 推送

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Zip files
      run: zip -r repo-files.zip .

    - name: Upload OpenWrt Firmware to Release
      uses: ncipollo/release-action@main
      if: ${{ env.PACKAGED_STATUS == 'success' }} && !cancelled()
      with:
        tag: OpenWrt_N1_${{ env.PACKAGED_OUTPUTDATE }}
        artifacts: ${{ steps.create_release.outputs.upload_url }}
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          基于lean openwrt构建
          首次使用建议全新刷写
          * 基本信息
          IP: 192.168.5.2
          账户: root
          密码: *********
